import * as fs from "fs";
import * as path from "path";
import type {
  DeclarationNode,
  DocumentNode,
  EnumNode,
  MethodNode,
  ServiceNode,
  StructNode,
} from "../../srpc-vscode/server/src/ast.ts";
import { parseDocumentSyntax } from "../../srpc-vscode/server/src/parser.ts";
import { scanContractFiles, type ContractFile } from "./scan.ts";
import { typeNodeToTs } from "./ts-type.ts";

export interface GenerateOptions {
  /** Directory containing `.ctr` / `.rpc` files. Defaults to `contract`. */
  contractDir?: string;
  /** Output `.ts` file path. Defaults to `generated/srpc-types.ts`. */
  outputFile?: string;
}

export interface GenerateStats {
  structs: number;
  enums: number;
  services: number;
  methods: number;
}

export interface GenerateResult {
  outputFile: string;
  contractDir: string;
  filesRead: string[];
  errors: string[];
  stats: GenerateStats;
}

interface ParsedContract {
  file: ContractFile;
  document: DocumentNode;
  errors: string[];
}

interface ServiceEntry {
  name: string;
  packageName: string;
  methods: MethodNode[];
}

export function generateFromContracts(
  options: GenerateOptions = {}
): GenerateResult {
  const contractDir = options.contractDir ?? "contract";
  const outputFile = options.outputFile ?? "generated/srpc-types.ts";

  const contractFiles = scanContractFiles(contractDir);
  const parsed = contractFiles.map(parseContractFile);
  const allErrors = parsed.flatMap(entry => entry.errors);

  const source = renderTypescript(parsed);
  writeOutput(outputFile, source);

  return {
    outputFile,
    contractDir,
    filesRead: contractFiles.map(file => file.relativePath),
    errors: allErrors,
    stats: countDeclarations(parsed),
  };
}

function countDeclarations(parsed: ParsedContract[]): GenerateStats {
  let structs = 0;
  let enums = 0;
  let services = 0;
  let methods = 0;

  for (const entry of parsed) {
    for (const decl of entry.document.declarations) {
      if (decl.kind === "struct") {
        structs++;
      } else if (decl.kind === "enum") {
        enums++;
      } else if (decl.kind === "service") {
        services++;
        methods += decl.methods.length;
      }
    }
  }

  return { structs, enums, services, methods };
}

function parseContractFile(file: ContractFile): ParsedContract {
  const result = parseDocumentSyntax(file.source);
  const errors = result.diagnostics
    .filter(diagnostic => diagnostic.severity === "error")
    .map(diagnostic => `${file.relativePath}: ${diagnostic.message}`);

  return {
    file,
    document: result.document,
    errors,
  };
}

function renderTypescript(parsed: ParsedContract[]): string {
  const lines: string[] = [
    "// Auto-generated by srpc-core. Do not edit.",
    'import type { SrpcServiceMeta } from "srpc-client";',
    "",
  ];

  const serviceEntries: ServiceEntry[] = [];

  for (const entry of parsed) {
    const { file, document } = entry;

    lines.push(`// ${file.relativePath}`);
    if (document.packageName) {
      lines.push(`// package ${document.packageName}`);
    }
    lines.push("");

    for (const decl of document.declarations) {
      if (decl.kind === "service") {
        serviceEntries.push({
          name: decl.name,
          packageName: document.packageName ?? "default",
          methods: decl.methods,
        });
        lines.push(renderServiceInterface(decl));
      } else {
        lines.push(renderDeclaration(decl));
      }
      lines.push("");
    }
  }

  if (serviceEntries.length > 0) {
    lines.push(renderServiceRegistry(serviceEntries));
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function renderDeclaration(decl: DeclarationNode): string {
  switch (decl.kind) {
    case "enum":
      return renderEnum(decl);
    case "struct":
      return renderStruct(decl);
    case "service":
      return renderServiceInterface(decl);
  }
}

function renderEnum(decl: EnumNode): string {
  const members = decl.values
    .map(value => `  ${value.name} = "${value.name}"`)
    .join(",\n");

  return `export enum ${decl.name} {\n${members},\n}`;
}

function renderStruct(decl: StructNode): string {
  const fields = decl.fields
    .map(
      field =>
        `  ${field.name}${field.optional ? "?" : ""}: ${typeNodeToTs(field.type)};`
    )
    .join("\n");

  return `export interface ${decl.name} {\n${fields}\n}`;
}

function renderServiceInterface(decl: ServiceNode): string {
  const methods = decl.methods
    .map(method => {
      const params = method.params
        .map(param => `${param.name}: ${typeNodeToTs(param.type)}`)
        .join(", ");

      return `  ${method.name}(${params}): ${typeNodeToTs(method.returnType)};`;
    })
    .join("\n");

  return `export interface ${decl.name} {\n${methods}\n}`;
}

function renderMethodMeta(method: MethodNode): string {
  const httpMethod = method.httpMethod ?? "POST";
  return `      ${method.name}: { httpMethod: "${httpMethod}" },`;
}

function renderServiceRegistry(services: ServiceEntry[]): string {
  const interfaceMap = services
    .map(service => `  ${service.name}: ${service.name};`)
    .join("\n");

  const registry = services
    .map(service => {
      const methods = service.methods.map(renderMethodMeta).join("\n");

      return `  ${service.name}: {
    package: "${service.packageName}",
    service: "${service.name}",
    methods: {
${methods}
    },
  } satisfies SrpcServiceMeta<${service.name}>,`;
    })
    .join("\n");

  const exports = services
    .map(
      service =>
        `export const ${service.name} = __srpcServices.${service.name} as SrpcServiceMeta<${service.name}, "${service.name}">;`
    )
    .join("\n");

  return `export type SrpcServiceInterfaces = {
${interfaceMap}
};

export type SrpcServiceName = keyof SrpcServiceInterfaces;

export const __srpcServices = {
${registry}
} as const;

${exports}`;
}

function writeOutput(outputFile: string, source: string): void {
  const resolved = path.resolve(outputFile);
  fs.mkdirSync(path.dirname(resolved), { recursive: true });
  fs.writeFileSync(resolved, source, "utf8");
}
